In [8]:
def binary_iter(arr: list,start: int ,end: int,target: int) -> int: 
    n = 1
    
    while start <= end:
        
        global mid 
           
        mid = (start + end)//2
        
        print(f'Value of mid variable before any loop is {mid}')
        
        if arr[mid] < target:
            start = mid + 1
            
        elif arr[mid] > target:
            end = mid - 1    
        else:
            return mid
        
        print(f'Value of mid variable after {n} run is {mid}, Value of start is {start}, end is {end}')
        n += 1
    return start

arr = [3,7,9,8,98,99,105,107,207]
target = 3
target_index = binary_iter(arr, 0, len(arr) - 1, target)
print(f'The position of our target is at index {target_index}')

Value of mid variable before any loop is 4
Value of mid variable after 1 run is 4, Value of start is 0, end is 3
Value of mid variable before any loop is 1
Value of mid variable after 2 run is 1, Value of start is 0, end is 0
Value of mid variable before any loop is 0
The position of our target is at index 0


In [9]:
import numpy as np

In [10]:
np.random.default_rng()

Generator(PCG64) at 0x7FCE92606820

In [11]:
np.random.seed(1)
np.random.randint(1,10,10)

array([6, 9, 6, 1, 1, 2, 8, 7, 3, 5])

In [12]:
rg = np.random.default_rng(2)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [13]:
f = np.ones(3, dtype=np.int32)
f

g = np.linspace(0, np.pi, 3)
f.dtype.name

'int32'

In [26]:
from calendar import *
year = 2022
print(calendar(year,3,1,8,4))

                                                                2022

          January                            February                            March                              April
Mon Tue Wed Thu Fri Sat Sun        Mon Tue Wed Thu Fri Sat Sun        Mon Tue Wed Thu Fri Sat Sun        Mon Tue Wed Thu Fri Sat Sun
                      1   2              1   2   3   4   5   6              1   2   3   4   5   6                          1   2   3
  3   4   5   6   7   8   9          7   8   9  10  11  12  13          7   8   9  10  11  12  13          4   5   6   7   8   9  10
 10  11  12  13  14  15  16         14  15  16  17  18  19  20         14  15  16  17  18  19  20         11  12  13  14  15  16  17
 17  18  19  20  21  22  23         21  22  23  24  25  26  27         21  22  23  24  25  26  27         18  19  20  21  22  23  24
 24  25  26  27  28  29  30         28                                 28  29  30  31                     25  26  27  28  29  30
 31

         

In [15]:
u = rg.random((3,3), dtype=np.float64)
u

array([[0.18790107, 0.05514663, 0.27496937],
       [0.65743301, 0.56226566, 0.15006226],
       [0.43263079, 0.6692973 , 0.42278467]])

In [16]:
l = np.arange(24).reshape((2, 3, 4))
l

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
lmax = l.min(axis=1)
lmax

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [18]:
del lmax

In [19]:
l

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
from enum import Enum

class Day(Enum):
    MONDAY = 1
    TUESDAY = 2
    WEDNESDAY = 3
    THURSDAY = 4
    FRIDAY = 5
    SATURDAY = 6
    SUNDAY = 7


list(Day)

[<Day.MONDAY: 1>,
 <Day.TUESDAY: 2>,
 <Day.WEDNESDAY: 3>,
 <Day.THURSDAY: 4>,
 <Day.FRIDAY: 5>,
 <Day.SATURDAY: 6>,
 <Day.SUNDAY: 7>]

In [21]:
type(Day)

enum.EnumMeta

In [22]:
type(Day.MONDAY)

<enum 'Day'>

In [23]:
len('medhan')

6

In [24]:
def far_to_cel() -> float:
    
    while True:
        
        
        
        try:
            Fahrenheit = float(input("Enter temperature in Fahrenheit: "))
            Celsius = (Fahrenheit - 32) * 5/9
            return Celsius
            
         
        except ValueError:
            print('Pls ensure you enter numbers only')
            
            
           
            


far_to_cel()

In [4]:
class Church:
    born_again = True   #class attribute common to all instances of this Class
    
    #instance attributes defined in the method below
    def __init__(self,name,department,gender,age):
        self.name = name
        self.department = department
        self.gender = gender
        self.age = age
    
    def member_info(self):
        return f"{self.name} is a member of the {self.department} department and is a {self.gender}"
        
    def member_list(self):
        
        if self.gender == 'female':
            female_group = {}
            female_group['name'] = self.name
            female_group['department'] = self.department
            female_group['age'] = self.age
        
            return f"{self.name} is a female member with the following info: {female_group}"
        else:
            male_group = {}
            male_group['name'] = self.name
            male_group['department'] = self.department
            male_group['age'] = self.age
            
            return f"{self.name} is a male member with the following info: {male_group}"
        
    def __str__(self):          #this method reads the instance of the Church class as a string and returns string below with a print statement or str function
        
        return f"This object is an instance of the Church class for member {self.name} obtained through the __str__ method"
    
    def __repr__(self):         #this method reads the instance of the Church class and returns string below when object is simply inspected
        
        return f"This object is an instance of the Church class for member {self.name} obtained through the __repr__ method"
        
            
            
            
            

In [6]:
Ajah_branch = Church('Tunde','Media','male',40)
Ajah_branch

This object is an instance of the Church class for member Tunde obtained through the __repr__ method

In [ ]:
Ajah_branch.department

'Media'

In [ ]:
Ajah_branch

This object is an instance of the Church class for member Tunde

In [ ]:
Ajah_branch.member_list()


"Tunde is a male member with the following info: {'name': 'Tunde', 'department': 'Media', 'age': 40}"

In [ ]:
Ajah_branch.gender = 'male'

In [ ]:
Ajah_branch.born_again

False

In [ ]:
Ajah_branch.gender

'male'

In [8]:
Akure_branch = Church('Sola', 'Pastor','male',50)

In [9]:
Akure_branch.gender

'male'

In [10]:
Akure_branch.member_list()

"Sola is a male member with the following info: {'name': 'Sola', 'department': 'Pastor', 'age': 50}"

In [13]:
Akure_branch.born_again = False
Akure_branch.born_again

False

In [16]:
class Pastorate(Church):        #Pastorate is child class of the parent class Church. Pastorate inherits all attributes and methods of Church
    #update instance method from Church class that is unique to Pastorate class
    def member_list(self):
        
        if self.gender == 'female':
            female_group = {}
            female_group['name'] = self.name
            female_group['department'] = self.department
            female_group['age'] = self.age
        
            return f"{self.name} is a female Pastor with the following info: {female_group}"
        else:
            male_group = {}
            male_group['name'] = self.name
            male_group['department'] = self.department
            male_group['age'] = self.age
            
            return f"{self.name} is a male Pastor with the following info: {male_group}"
    
    #define a new method for the Pastorate class
    
    def ministry_years(self,yrs_ministry):
        
        return f"Years of ministry is {experience}"
        

In [ ]:
pastor_D = Pastorate("Damilola","Pastor","male",44)
pastor_D.member_list()

"Damilola is a male Pastor with the following info: {'name': 'Damilola', 'department': 'Pastor', 'age': 44}"

In [ ]:
pastor_A = Pastorate('Austin','Pastor','male',59)
pastor_A.member_info()

'Austin is a member of the Pastor department and is a male'

In [ ]:
pastor_A.ministry_years(6)

'Years of ministry is 6'

In [ ]:
pastor_D.ministry_years(10)

'Years of ministry is 10'

In [ ]:
isinstance(pastor_D,Pastorate)

True

In [ ]:
class ChlidrenChurch(Church):
    pass

In [ ]:
jola = ChlidrenChurch("Jolaoluwa","David Army",'female', 9)

In [ ]:
isinstance(jola,Church)

True

In [ ]:
jola.member_list()

"Jolaoluwa is a female member with the following info: {'name': 'Jolaoluwa', 'department': 'David Army', 'age': 9}"

In [27]:
class Rectangle:
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

    def perimeter(self):
        return 2 * self.length + 2 * self.width

# Here we declare that the Square class inherits from the Rectangle class
class Square(Rectangle):
    def __init__(self, length):
        super().__init__(length, length)

In [31]:
sq_solution = Square(7)
sq_solution.perimeter()

28

In [ ]:
test_dict = {'name': 'Tunde', 'age': 44, 'skin color': 'dark'}
test_dict2 = {'age': 44, 'name': 'Tunde', 'skin color': 'dark'}
test_dict['years on earth'] = test_dict.pop('age')
test_dict.items()

dict_items([('name', 'Tunde'), ('skin color', 'dark'), ('years on earth', 44)])

In [ ]:
for i, j in test_dict2.items():
    print(f"Key is {i} and Value is {j}")

Key is age and Value is 44
Key is name and Value is Tunde
Key is skin color and Value is dark


In [ ]:
new_dict = test_dict
test_dict.update({'food':'yam'})
new_dict

{'name': 'Tunde', 'skin color': 'dark', 'years on earth': 44, 'food': 'yam'}

In [ ]:
new_dict['car'] = 'toyota'

In [ ]:
copy_dict = test_dict.copy()
copy_dict

{'name': 'Tunde',
 'skin color': 'dark',
 'years on earth': 44,
 'food': 'yam',
 'car': 'toyota'}

In [ ]:
dict(("py", "th", "on"))

{'p': 'y', 't': 'h', 'o': 'n'}

In [14]:
m = dict((['one',1],['two',2],['three',3]))
m

{'one': 1, 'two': 2, 'three': 3}

In [ ]:
key_val = ('one', 'two', 'three')
value_val = (1,2,3)
for i in value_val:
    thisdict = dict.fromkeys(key_val, i)
thisdict

{'one': 3, 'two': 3, 'three': 3}

In [ ]:
for h in [1,2,3]:
    print(h)

1
2
3


In [ ]:
copy_dict['fave food'] = copy_dict.pop('food')
copy_dict

{'name': 'Tunde',
 'skin color': 'dark',
 'years on earth': 44,
 'car': 'toyota',
 'fave food': 'yam'}

In [19]:
d = {'x':1, 'y':2, 'z':3}
d1 = {'x':'a', 'y':'b', 'z':'c'}

dict((d1[key], value) for (key, value) in d.items())

{'a': 1, 'b': 2, 'c': 3}

In [21]:
for letters in d:
    print(letters)

x
y
z


In [ ]:
round(1.5) = round(2.5)

SyntaxError: cannot assign to function call (3961008226.py, line 1)

In [18]:
import numpy as np
np.random.rand(100,5)

array([[1.44032795e-01, 8.75131952e-01, 7.88875081e-01, 7.61416686e-01,
        6.00759006e-01],
       [4.35800495e-01, 9.90989584e-01, 3.49129323e-01, 1.29641888e-01,
        2.96541467e-02],
       [1.36990601e-01, 1.61072959e-01, 8.12484297e-01, 5.07683278e-01,
        5.12515233e-02],
       [7.69584066e-01, 6.01277325e-01, 6.89137479e-01, 3.60336355e-01,
        7.38381408e-01],
       [3.70299618e-01, 4.54287089e-01, 8.90175500e-01, 8.89359035e-01,
        8.79967555e-01],
       [1.78931465e-01, 4.62084850e-02, 2.75440157e-01, 2.95043176e-01,
        4.23352469e-01],
       [9.27196866e-01, 3.42371472e-01, 8.26093341e-01, 6.96663709e-01,
        5.88536302e-01],
       [2.13784651e-01, 7.89652050e-01, 7.80646481e-01, 6.46267190e-01,
        3.46060082e-01],
       [6.85003353e-01, 7.99697115e-01, 9.08288998e-01, 1.99490775e-01,
        1.66513578e-01],
       [6.85185765e-01, 2.44764001e-01, 2.24356531e-02, 9.46305823e-01,
        5.31694916e-01],
       [9.71797745e-01, 9.4323